/*
 * linux/arch/arm/mach-omap2/mux_archer.c
 *
 * NOTE: See mux_index.h for the enumeration
 */
//#define FEATURE_SUSPEND_BY_DISABLING_POWER

unsigned int output_gpio[][2] = {
//	{ GPIO NUMBER      , DEFAULT VALUE }	
#if 0
{ OMAP_GPIO_FM_INT	    ,0 },
//{ OMAP_GPIO_USBSW_NINT        ,0 },
{ OMAP_GPIO_AP_NAND_INT       ,0 },
{ OMAP_GPIO_AP_ALARM          ,0 },
//{ OMAP_GPIO_INT_ONEDRAM_AP    ,0 },
{ OMAP_GPIO_CHG_ING_N         ,0 },
{ OMAP_GPIO_WLAN_IRQ          ,0 },
{ OMAP_GPIO_SYS_DRM_MSECURE   ,0 },
//{ OMAP_GPIO_TF_DETECT         ,0 },
{ OMAP_GPIO_PS_HOLD_PU        ,1 },
//{ OMAP_GPIO_EAR_KEY           ,0 },
//{ OMAP_GPIO_DET_3_5           ,0 },
{ OMAP_GPIO_PCM_SEL	    ,0 },
{ OMAP_GPIO_PS_OUT            ,0 },
{ OMAP_GPIO_IF_CON_SENSE      ,0 },
{ OMAP_GPIO_VF	 	    ,0 },
{ OMAP_GPIO_BT_NSHUTDOWN      ,0 },
{ OMAP_GPIO_VGA_RST        ,0 },
{ OMAP_GPIO_FM_nRST	    ,0 },
{ OMAP_GPIO_CAM_RST           ,0 },
{ OMAP_GPIO_LCD_REG_RST       ,0 },
{ OMAP_GPIO_ISP_INT           ,0 },
{ OMAP_GPIO_VGA_STBY          ,0 },
{ OMAP_GPIO_PDA_ACTIVE        ,0 },
{ OMAP_GPIO_ACC_INT           ,0 },
{ OMAP_GPIO_UART_SEL          ,0 },
{ OMAP_GPIO_FONE_ON	    ,0 },
{ OMAP_GPIO_MOTOR_EN          ,0 },
{ OMAP_GPIO_TOUCH_IRQ         ,0 },
{ OMAP_GPIO_USB_SEL           ,0 },
{ OMAP_GPIO_RGB_RST	    ,1 },
{ OMAP_GPIO_CAM_EN            ,0 },
{ OMAP_GPIO_PHONE_ACTIVE      ,0 },
{ OMAP_GPIO_MOVI_EN	    ,0 },
{ OMAP_GPIO_HW_REV0           ,0 },
{ OMAP_GPIO_CHG_EN            ,1 },
{ OMAP_GPIO_HW_REV1           ,0 },
{ OMAP_GPIO_HW_REV2           ,0 },
{ OMAP_GPIO_WLAN_EN           ,0 },
{ OMAP_GPIO_LCD_ID            ,0 },
{ OMAP_GPIO_EAR_MIC_LDO_EN    ,0 },
{ OMAP_GPIO_CAMERA_LEVEL_CTRL ,0 },
{ OMAP_GPIO_MLCD_RST          ,1 },
{ OMAP_GPIO_TVOUT_SEL         ,0 },
{ OMAP_GPIO_MSM_RST18_N       ,1 },

#endif
};


unsigned int wakeup_gpio[] = {
#if 1
	OMAP_GPIO_USBSW_NINT,
	OMAP_GPIO_INT_ONEDRAM_AP,
	OMAP_GPIO_TF_DETECT,
	OMAP_GPIO_KEY_PWRON,
	OMAP_GPIO_EAR_KEY,
	OMAP_GPIO_DET_3_5,
#endif
};


#if 0 //def CONFIG_MACH_SAMSUNG_NOWPLUS
static struct omap_board_mux board_mux[] __initdata = {
        OMAP3_MUX(SDRC_D0,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D1,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D2,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D3,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D4,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D5,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D6,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D7,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D8,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D9,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D10,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D11,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D12,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D13,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D14,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D15,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D16,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D17,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D18,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D19,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D20,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D21,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D22,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D23,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D24,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D25,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D26,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D27,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D28,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D29,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D30,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_D31,             OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_CKE0,            OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_CKE1,            OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_CLK,             OMAP34XX_MUX_MODE0),
        OMAP3_MUX(SDRC_DQS0,            OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_DQS1,            OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_DQS2,            OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SDRC_DQS3,            OMAP34XX_PIN_INPUT),

        OMAP3_MUX(GPMC_A1,                      OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_A2,                      OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_A3,                      OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_A4,                      OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_A5,                      OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_A6,                      OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_A7,                      OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_A8,                      OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_A9,                      OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_A10,                     OMAP34XX_MUX_MODE7),

        //"GPMC D0"
        OMAP3_MUX(GPMC_D0,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D1"
        OMAP3_MUX(GPMC_D1,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D2"
        OMAP3_MUX(GPMC_D2,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D3"
        OMAP3_MUX(GPMC_D3,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D4"
        OMAP3_MUX(GPMC_D4,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D5" 
        OMAP3_MUX(GPMC_D5,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D6"
        OMAP3_MUX(GPMC_D6,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D7"
        OMAP3_MUX(GPMC_D7,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D8"
        OMAP3_MUX(GPMC_D8,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D9"
        OMAP3_MUX(GPMC_D9,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D10"
        OMAP3_MUX(GPMC_D10,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D11"
        OMAP3_MUX(GPMC_D11,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D12"
        OMAP3_MUX(GPMC_D12,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D13"
        OMAP3_MUX(GPMC_D13,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D14"
        OMAP3_MUX(GPMC_D14,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"GPMC D15"
        OMAP3_MUX(GPMC_D15,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
	    //"GPMC CS0"
        OMAP3_MUX(GPMC_NCS0,            OMAP34XX_MUX_MODE0 ),
        
        //"PCMSEL" gpio_52
        OMAP3_MUX(GPMC_NCS1,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"PROXIMITY INT" gpio_53
        OMAP3_MUX(GPMC_NCS2,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN ),
        //"IF CON" gpio_54
        OMAP3_MUX(GPMC_NCS3,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN ),
        //"DPRAM CS"
        OMAP3_MUX(GPMC_NCS4,            OMAP34XX_MUX_MODE7),
        //"VF" gpio_56
        OMAP3_MUX(GPMC_NCS5,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        OMAP3_MUX(GPMC_NCS6,            OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_NCS7,            OMAP34XX_MUX_MODE7),
        OMAP3_MUX(GPMC_CLK,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        OMAP3_MUX(GPMC_NADV_ALE,        OMAP34XX_MUX_MODE0),
	    
	    //"GPMC NOE"    
        OMAP3_MUX(GPMC_NOE,             OMAP34XX_MUX_MODE0),
        //"GPMC NWE"
        OMAP3_MUX(GPMC_NWE,             OMAP34XX_MUX_MODE0),

        OMAP3_MUX(GPMC_NBE0_CLE,        OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT),
        OMAP3_MUX(GPMC_NBE1,            OMAP34XX_MUX_MODE7 | OMAP34XX_PIN_INPUT_PULLDOWN),
        OMAP3_MUX(GPMC_NWP,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT),
        OMAP3_MUX(GPMC_WAIT0,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP),
        //"BT_nSHUTDOWN" gpio_63	
        OMAP3_MUX(GPMC_WAIT1,           OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"CAMERA VGA RST" gpio_64
        OMAP3_MUX(GPMC_WAIT2,           OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"FM_nRST" gpio_65
        OMAP3_MUX(GPMC_WAIT3,           OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),

        //"LCD MCLK"
        OMAP3_MUX(DSS_PCLK,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD HSYNC"        
        OMAP3_MUX(DSS_HSYNC,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD VSYNC"
        OMAP3_MUX(DSS_VSYNC,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD CE"
        OMAP3_MUX(DSS_ACBIAS,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
	
        //"LCD DAT<0>"	        
        OMAP3_MUX(DSS_DATA0,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),        
        //"LCD DAT<1>"
        OMAP3_MUX(DSS_DATA1,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<2>"
        OMAP3_MUX(DSS_DATA2,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<3>"
        OMAP3_MUX(DSS_DATA3,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<4>"
        OMAP3_MUX(DSS_DATA4,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<5>"
        OMAP3_MUX(DSS_DATA5,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<6>"
        OMAP3_MUX(DSS_DATA6,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<7>"
        OMAP3_MUX(DSS_DATA7,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<8>"
        OMAP3_MUX(DSS_DATA8,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<9>"
        OMAP3_MUX(DSS_DATA9,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<10>"
        OMAP3_MUX(DSS_DATA10,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<11>"
        OMAP3_MUX(DSS_DATA11,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<12>"
        OMAP3_MUX(DSS_DATA12,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<13>"
        OMAP3_MUX(DSS_DATA13,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<14>"
        OMAP3_MUX(DSS_DATA14,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<15>"
        OMAP3_MUX(DSS_DATA15,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<16>"
        OMAP3_MUX(DSS_DATA16,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<17>"
        OMAP3_MUX(DSS_DATA17,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<18>"
        OMAP3_MUX(DSS_DATA18,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<19>"
        OMAP3_MUX(DSS_DATA19,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<20>"
        OMAP3_MUX(DSS_DATA20,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<21>"
        OMAP3_MUX(DSS_DATA21,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<22>"
        OMAP3_MUX(DSS_DATA22,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"LCD DAT<23>"
        OMAP3_MUX(DSS_DATA23,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_OUTPUT_LOW),

        //"PIXEL HSYNC"
        OMAP3_MUX(CAM_HS,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"PIXEL VSYNC"
        OMAP3_MUX(CAM_VS,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"PIXEL MCLK"
        OMAP3_MUX(CAM_XCLKA,            OMAP34XX_MUX_MODE0),
        //"PIXEL PCLK"
        OMAP3_MUX(CAM_PCLK,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"CAMERA RESET" gpio_98
        OMAP3_MUX(CAM_FLD,              OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
	    //"LCD REG RST" gpio_99
        OMAP3_MUX(CAM_D0,               OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        //"ISP INTERRUPT" gpio_100
        OMAP3_MUX(CAM_D1,               OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"CAMERA VGA STBY" gpio_101
        OMAP3_MUX(CAM_D2,               OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        OMAP3_MUX(CAM_D3,               OMAP34XX_MUX_MODE7),
        
	    //"CAM DD<0>"
		OMAP3_MUX(CAM_D4,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
		//"CAM DD<1>"
        OMAP3_MUX(CAM_D5,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"CAM DD<2>"
        OMAP3_MUX(CAM_D6,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"CAM DD<3>"
        OMAP3_MUX(CAM_D7,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"CAM DD<4>"
        OMAP3_MUX(CAM_D8,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"CAM DD<5>"
        OMAP3_MUX(CAM_D9,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"CAM DD<6>"
        OMAP3_MUX(CAM_D10,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"CAM DD<7>"
        OMAP3_MUX(CAM_D11,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"PDA ACTIVE" gpio_111
        OMAP3_MUX(CAM_XCLKB,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        //"CAMERA LEVEL CTRL" gpio_112
        OMAP3_MUX(CAM_WEN,              OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        //"UART SEL" gpio_113
        OMAP3_MUX(CAM_STROBE,           OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),

	    OMAP3_MUX(CSI2_DX0,             OMAP34XX_MUX_MODE7),
        OMAP3_MUX(CSI2_DY0,             OMAP34XX_MUX_MODE7),
	    OMAP3_MUX(CSI2_DX1,             OMAP34XX_MUX_MODE7),
	    //"ACC_INT" gpio_115
        OMAP3_MUX(CSI2_DY1,             OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"MCBSP2 Sync"
        OMAP3_MUX(MCBSP2_FSX,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"MCBSP2 Clock"
        OMAP3_MUX(MCBSP2_CLKX,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"MCBSP2 Dout"
        OMAP3_MUX(MCBSP2_DR,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"MCBSP2 Din"
        OMAP3_MUX(MCBSP2_DX,            OMAP34XX_MUX_MODE0),

	    //"MMC1 CLK"
		OMAP3_MUX(SDMMC1_CLK,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_OUTPUT_LOW),
		//"MMC1 CMD"
        OMAP3_MUX(SDMMC1_CMD,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_OUTPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"MMC1 D0"
        OMAP3_MUX(SDMMC1_DAT0,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"MMC1 D1"
        OMAP3_MUX(SDMMC1_DAT1,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"MMC1 D2"
        OMAP3_MUX(SDMMC1_DAT2,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"MMC1 D3"
        OMAP3_MUX(SDMMC1_DAT3,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SDMMC1_DAT4,          OMAP34XX_MUX_MODE7),
        OMAP3_MUX(SDMMC1_DAT5,          OMAP34XX_MUX_MODE7),
        OMAP3_MUX(SDMMC1_DAT6,          OMAP34XX_MUX_MODE7),
        OMAP3_MUX(SDMMC1_DAT7,          OMAP34XX_MUX_MODE7),

        //"MOVI CLOCK"
 	    OMAP3_MUX(SDMMC2_CLK,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_OUTPUT_LOW),
 	    //"MOVI COMMAND"
        OMAP3_MUX(SDMMC2_CMD,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"MOVI DATA 0"
        OMAP3_MUX(SDMMC2_DAT0,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"MOVI DATA 1"
        OMAP3_MUX(SDMMC2_DAT1,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"MOVI DATA 2"
        OMAP3_MUX(SDMMC2_DAT2,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"MOVI DATA 3"
        OMAP3_MUX(SDMMC2_DAT3,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"MOVI DATA 4"
        OMAP3_MUX(SDMMC2_DAT4,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"MOVI DATA 5"
        OMAP3_MUX(SDMMC2_DAT5,          OMAP34XX_MUX_MODE7),
        //"MOVI DATA 6"
        OMAP3_MUX(SDMMC2_DAT6,          OMAP34XX_MUX_MODE7),
        //"MOVI DATA 7"
        OMAP3_MUX(SDMMC2_DAT7,          OMAP34XX_MUX_MODE7),

        //"FONE ON" gpio_140
        OMAP3_MUX(MCBSP3_DX,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"MOTOR EN" gpio_141
        OMAP3_MUX(MCBSP3_DR,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_OUTPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"TOUCH INT" gpio_142
        OMAP3_MUX(MCBSP3_CLKX,          OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_NONE),
    	OMAP3_MUX(MCBSP3_FSX,           OMAP34XX_MUX_MODE7),

	    //"BTUART CTS"
        OMAP3_MUX(UART2_CTS,            OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT), 
        
         //"BTUART RTS"
        OMAP3_MUX(UART2_RTS,            OMAP34XX_MUX_MODE0), 
         //"BTUART TXD"
       OMAP3_MUX(UART2_TX,             OMAP34XX_MUX_MODE0), 
         //"BTUART RXD"
        OMAP3_MUX(UART2_RX,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP), 
        OMAP3_MUX(UART1_TX,             OMAP34XX_MUX_MODE7),
        OMAP3_MUX(UART1_RTS,            OMAP34XX_MUX_MODE7),
        //"USB SEL" gpio_150
        OMAP3_MUX(UART1_CTS,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"RGB RST" gpio_151
        OMAP3_MUX(UART1_RX,             OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        //"CAMERA EN" gpio_152
        OMAP3_MUX(MCBSP4_CLKX,          OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
    	OMAP3_MUX(MCBSP4_DR,            OMAP34XX_MUX_MODE7),
    	//"PHONE ACTIVE" gpio_154
        OMAP3_MUX(MCBSP4_DX,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT), 
        //"MOVI POWER EN" gpio_155
        OMAP3_MUX(MCBSP4_FSX,           OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_OUTPUT),
        //"HW REV0" gpio_156
        OMAP3_MUX(MCBSP1_CLKR,          OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT),
        //"TA Enable" gpio_157
        OMAP3_MUX(MCBSP1_FSR,           OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN ),
        //"HW REV1" gpio_158
        OMAP3_MUX(MCBSP1_DX,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT),
        //"HW REV2" gpio_159
        OMAP3_MUX(MCBSP1_DR,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT),
		//"WLAN EN" gpio_160
		OMAP3_MUX(MCBSP_CLKS,           OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
		//"LCD ID" gpio_161
        OMAP3_MUX(MCBSP1_FSX,           OMAP34XX_MUX_MODE7 ),
        //"EAR MIC PWR EN" gpio_162
        OMAP3_MUX(MCBSP1_CLKX,          OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),

        OMAP3_MUX(UART3_CTS_RCTX,       OMAP34XX_MUX_MODE7),
        OMAP3_MUX(UART3_RTS_SD,         OMAP34XX_MUX_MODE7), 
        //"UART1 RXD"
        OMAP3_MUX(UART3_RX_IRRX,        OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_OUTPUT_LOW ),
        //"UART1 TXD"
        OMAP3_MUX(UART3_TX_IRTX,        OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_OFF_OUTPUT_LOW),

        // HSUSB SIGNALS - skip
        //"USB CLK"
        OMAP3_MUX(HSUSB0_CLK,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"USB STP"
        OMAP3_MUX(HSUSB0_STP,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_OUTPUT_HIGH),
        //"USB DIR"
        OMAP3_MUX(HSUSB0_DIR,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"USB NEXT"
        OMAP3_MUX(HSUSB0_NXT,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"USB DATA0"
        OMAP3_MUX(HSUSB0_DATA0,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"USB DATA1"
        OMAP3_MUX(HSUSB0_DATA1,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"USB DATA2"
        OMAP3_MUX(HSUSB0_DATA2,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"USB DATA3"
        OMAP3_MUX(HSUSB0_DATA3,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"USB DATA4"
        OMAP3_MUX(HSUSB0_DATA4,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"USB DATA5"
        OMAP3_MUX(HSUSB0_DATA5,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"USB DATA6"
        OMAP3_MUX(HSUSB0_DATA6,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"USB DATA7"
        OMAP3_MUX(HSUSB0_DATA7,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),

        //"PWR I2C SCL"
        OMAP3_MUX(I2C1_SCL,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP),
        //"PWR I2C SDA"
        OMAP3_MUX(I2C1_SDA,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP),
        
        //"I2C SCL"
        OMAP3_MUX(I2C2_SCL,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP),
        //"I2C SDA"
        OMAP3_MUX(I2C2_SDA,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP),

        //"TOUCH I2C SCL"
        OMAP3_MUX(I2C3_SCL,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_NONE),
        //"TOUCH I2C SDA"
        OMAP3_MUX(I2C3_SDA,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_NONE),
        //"MLCD RST" gpio_170
        OMAP3_MUX(HDQ_SIO,              OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        //"DISPLAY CLK"
        OMAP3_MUX(MCSPI1_CLK,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"DISPLAY SI"
        OMAP3_MUX(MCSPI1_SIMO,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"DISPLAY SO"
        OMAP3_MUX(MCSPI1_SOMI,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"DISPLAY CS"
        OMAP3_MUX(MCSPI1_CS0,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
	    //"WLAN SDIO CMD"
        OMAP3_MUX(MCSPI1_CS1,           OMAP34XX_MUX_MODE3 | OMAP34XX_PIN_INPUT_PULLUP),
            //"WLAN SDIO CLK"
        OMAP3_MUX(MCSPI1_CS2,           OMAP34XX_MUX_MODE3 | OMAP34XX_PIN_INPUT_PULLUP),
            //"TVOUT SEL" gpio_177
        OMAP3_MUX(MCSPI1_CS3,           OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"PHONE RESET" gpio_178
        OMAP3_MUX(MCSPI2_CLK,           OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        //"VIB FREQ"
        OMAP3_MUX(MCSPI2_SIMO,          OMAP34XX_MUX_MODE1 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
    	OMAP3_MUX(MCSPI2_SOMI,          OMAP34XX_MUX_MODE7),
        OMAP3_MUX(MCSPI2_CS0,           OMAP34XX_MUX_MODE7),
        OMAP3_MUX(MCSPI2_CS1,           OMAP34XX_MUX_MODE7),

	    //"SYS nIRQ"
        OMAP3_MUX(SYS_NIRQ,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP3_WAKEUP_EN),
    	OMAP3_MUX(SYS_CLKOUT2,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD0,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD1,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD2,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD3,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD4,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD5,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD6,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD7,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD8,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD9,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD10,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD11,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD12,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD13,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD14,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD15,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD16,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD17,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD18,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD19,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD20,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD21,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD22,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD23,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD24,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD25,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD26,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD27,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD28,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD29,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD30,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD31,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD32,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD33,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD34,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD35,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MCAD36,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_CLK26MI,      OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        OMAP3_MUX(CHASSIS_NRESPWRON,    OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        //"WARM RESET"
        OMAP3_MUX(CHASSIS_NRESWARW,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLUP),
        OMAP3_MUX(CHASSIS_NIRQ,                 OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        OMAP3_MUX(CHASSIS_FIQ,                  OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_OUTPUT_LOW),
        OMAP3_MUX(CHASSIS_ARMIRQ,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_IVAIRQ,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_DMAREQ0,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_DMAREQ1,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_DMAREQ2,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_DMAREQ3,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),

        OMAP3_MUX(CHASSIS_NTRST,                OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_TDI,                  OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_TDO,                  OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_TMS,                  OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_TCK,                  OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_RTCK,                 OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_MSTDBY,               OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_INPUT_PULLUP),
        OMAP3_MUX(CHASSIS_IDLEREQ,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(CHASSIS_IDLEACK,              OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_INPUT_PULLUP),

        OMAP3_MUX(SAD2D_MWRITE,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_SWRITE,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MREAD,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_SREAD,          OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_MBUSFLAG,       OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        OMAP3_MUX(SAD2D_SBUSFLAG,       OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        
        //"SR I2C SCL"
        OMAP3_MUX(I2C4_SCL,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP),
        //"SR I2C SDA"
        OMAP3_MUX(I2C4_SDA,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP),

        OMAP3_MUX(SYS_32K,              OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SYS_CLKREQ,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT),
        OMAP3_MUX(SYS_NRESWARM,         OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT),
	
        OMAP3_MUX(SYS_BOOT0,            OMAP34XX_MUX_MODE7),
        //"FM_INT" gpio_3	
        OMAP3_MUX(SYS_BOOT1,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //gpio_4
        OMAP3_MUX(SYS_BOOT2,            OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN),
        //"SYS BOOT3"
        OMAP3_MUX(SYS_BOOT3,            OMAP34XX_MUX_MODE7 ),
        //"SYS BOOT4"
        OMAP3_MUX(SYS_BOOT4,            OMAP34XX_MUX_MODE7 ),
        //"SYS BOOT5"
        OMAP3_MUX(SYS_BOOT5,            OMAP34XX_MUX_MODE7 ),
        //"SYS BOOT6"
        OMAP3_MUX(SYS_BOOT6,            OMAP34XX_MUX_MODE7 ),
        //"SYS OFF"
        OMAP3_MUX(SYS_OFF_MODE,         OMAP34XX_MUX_MODE0),
        //"MICRO nINT" gpio_10
        OMAP3_MUX(SYS_CLKOUT1,          OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP | OMAP3_WAKEUP_EN),

        OMAP3_MUX(JTAG_NTRST,           OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        OMAP3_MUX(JTAG_TCK,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLDOWN),
        OMAP3_MUX(JTAG_TMS_TMSC,        OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP),
        OMAP3_MUX(JTAG_TDI,             OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT_PULLUP),
        OMAP3_MUX(JTAG_EMU0,            OMAP34XX_MUX_MODE7),
        OMAP3_MUX(JTAG_EMU1,            OMAP34XX_MUX_MODE7),
        //"LOW BAT DET" gpio_12
        OMAP3_MUX(ETK_CLK,                      OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP | OMAP3_WAKEUP_EN),
        //"NAND INT" gpio_13
        OMAP3_MUX(ETK_CTL,                      OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        //"ALARM_AP" gpio_14
        OMAP3_MUX(ETK_D0,                       OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        //"INTERRUPT FROM PHONE"  gpio_15
        OMAP3_MUX(ETK_D1,                       OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP | OMAP3_WAKEUP_EN),
        //"TA nCHG"  gpio_16
        OMAP3_MUX(ETK_D2,                       OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
	    //"WLAN SDIO DAT0"
        OMAP3_MUX(ETK_D3,                       OMAP34XX_MUX_MODE2 | OMAP34XX_PIN_INPUT_PULLUP),
           //"WLAN SDIO DAT1"
        OMAP3_MUX(ETK_D4,                       OMAP34XX_MUX_MODE2 | OMAP34XX_PIN_INPUT_PULLUP),
          //"WLAN SDIO DAT2"
        OMAP3_MUX(ETK_D5,                       OMAP34XX_MUX_MODE2 | OMAP34XX_PIN_INPUT_PULLUP),
          //"WLAN SDIO DAT3"
        OMAP3_MUX(ETK_D6,                       OMAP34XX_MUX_MODE2 | OMAP34XX_PIN_INPUT_PULLUP),
        //"WLAN IRQ"
        OMAP3_MUX(ETK_D7,                       OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP | OMAP34XX_PIN_OFF_INPUT_PULLDOWN),
        //"TWL4030 MSECURE"
        OMAP3_MUX(ETK_D8,                       OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        //"MMC1 DETECT"
        OMAP3_MUX(ETK_D9,                       OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT),
        //"KEY PWRON"
        OMAP3_MUX(ETK_D10,                      OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLDOWN | OMAP3_WAKEUP_EN),        
        //"PS HOLD"
        OMAP3_MUX(ETK_D11,                      OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP),
        //"EARKEY DETECT"
        OMAP3_MUX(ETK_D12,                      OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT | OMAP3_WAKEUP_EN),
        //"35PI DETECT"
        OMAP3_MUX(ETK_D13,                      OMAP34XX_MUX_MODE4 | OMAP34XX_PIN_INPUT_PULLUP | OMAP3_WAKEUP_EN),
        OMAP3_MUX(ETK_D14,                      OMAP34XX_MUX_MODE7),
        
        //"NO USED"
        OMAP3_MUX(ETK_D15,                      OMAP34XX_MUX_MODE7),

        OMAP3_MUX(SAD2D_SWAKEUP,        OMAP34XX_MUX_MODE0 | OMAP34XX_PIN_INPUT),

        { .reg_offset = OMAP_MUX_TERMINATOR },
};
#define OMAP_PINS_SZ	ARRAY_SIZE(board_mux)

#else
#define OMAP_pins		NULL
#define OMAP_PINS_SZ	0
#endif

